version: "3"

services:
  alive:
    image: sheyabernstein/alive:latest
    container_name: alive
    restart: unless-stopped
    build:
      context: .
      target: app
    ports:
      - "4444:4444"
    healthcheck:
      test: "wget --spider -q http://127.0.0.1:4444/healthz || exit 1"
      interval: 15s
      retries: 4
      start_period: 15s
      timeout: 10s
